services:
  rest_grpc_server:
    build:
      context: .
      dockerfile: Dockerfile.rest_grpc
    ports:
      - "3000:3000"    # REST
      - "50051:50051"  # gRPC
    volumes:
      - ./mercadorias.json:/app/mercadorias.json
    restart: always

  soap_server:
    build:
      context: .
      dockerfile: Dockerfile.soap
    ports:
      - "3001:3001"
    volumes:
      - ./mercadorias.json:/app/mercadorias.json
    restart: always

  graphql_server:
    build:
      context: .
      dockerfile: Dockerfile.graphql
    ports:
      - "3002:3002"
    volumes:
      - ./mercadorias.json:/app/mercadorias.json
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - rest_grpc_server
    restart: always
